- hosts: localhost
  tasks:

# use case when esxi.single_vswitch is false

    - name: Migrate vmk1 (VMotion) to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
        username: "administrator@{{ vcenter.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        validate_certs: false
        esxi_hostname: "{{ item }}"
        device: 'vmk1'
        current_switch_name: 'vSwitch1'
        current_portgroup_name: 'VMotion Network'
        migrate_switch_name: "{{ vcenter.dvs.basename }}-1-VMotion"
        migrate_portgroup_name: "{{ vcenter.dvs.portgroup.VMotion.name }}"
      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
      when: esxi.single_vswitch is false

    - name: Migrate vmk2 (VSAN) to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
        username: "administrator@{{ vcenter.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        validate_certs: false
        esxi_hostname: "{{ item }}"
        device: 'vmk2'
        current_switch_name: 'vSwitch2'
        current_portgroup_name: 'VSAN Network'
        migrate_switch_name: "{{ vcenter.dvs.basename }}-2-VSAN"
        migrate_portgroup_name: "{{ vcenter.dvs.portgroup.VSAN.name }}"
      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
      when: esxi.single_vswitch is false

#    - name: Migrate vmk0 (Mgmt) to the VDS
#      community.vmware.vmware_migrate_vmk:
#        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
#        username: "administrator@{{ vcenter.sso.domain_name }}"
#        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
#        validate_certs: false
#        esxi_hostname: "{{ item }}"
#        device: 'vmk0'
#        current_switch_name: 'vSwitch0'
#        current_portgroup_name: 'Management Network'
#        migrate_switch_name: "{{ vcenter.dvs.basename }}-0-mgmt"
#        migrate_portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
#      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
#      register: result
#      until: result is not failed
#      retries: 5
#      delay: 10
#      when: esxi.single_vswitch is false

#    - name: Add Management vmkernel port using static network type for vmk3
#      community.vmware.vmware_vmkernel:
#        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
#        username: "administrator@{{ vcenter.sso.domain_name }}"
#        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
#        validate_certs: false
#        device: vmk3
#        esxi_hostname: "{{ item.0 }}"
#        dvswitch_name: "{{ vcenter.dvs.basename }}-0"
#        portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
#        network:
#          type: 'static'
#          ip_address: "{{ item.1 }}"
#          subnet_mask: "{{ vcenter.dvs.portgroup.management.netmask }}"
#        state: present
#        enable_mgmt: True
#      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips | zip(vcenter.dvs.portgroup.management.esxi_ips_temp) | list }}"
#      when: esxi.single_vswitch is false
#
#    - name: Add Management vmkernel port using static network type for vmk4
#      community.vmware.vmware_vmkernel:
#        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
#        username: "administrator@{{ vcenter.sso.domain_name }}"
#        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
#        validate_certs: false
#        device: vmk4
#        esxi_hostname: "{{ item }}"
#        dvswitch_name: "{{ vcenter.dvs.basename }}-0"
#        portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
#        network:
#          type: 'dhcp'
#        state: present
#        enable_mgmt: True
#      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
#      when: esxi.single_vswitch is false

# use case when esxi.single_vswitch is true

    - name: Migrate vmk1 (VMotion) to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
        username: "administrator@{{ vcenter.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        validate_certs: false
        esxi_hostname: "{{ item }}"
        device: 'vmk1'
        current_switch_name: 'vSwitch1'
        current_portgroup_name: 'VMotion Network'
        migrate_switch_name: "{{ vcenter.dvs.basename }}-0"
        migrate_portgroup_name: "{{ vcenter.dvs.portgroup.VMotion.name }}"
      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
      when: esxi.single_vswitch is true

    - name: Migrate vmk2 (VSAN) to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
        username: "administrator@{{ vcenter.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        validate_certs: false
        esxi_hostname: "{{ item }}"
        device: 'vmk2'
        current_switch_name: 'vSwitch2'
        current_portgroup_name: 'VSAN Network'
        migrate_switch_name: "{{ vcenter.dvs.basename }}-0"
        migrate_portgroup_name: "{{ vcenter.dvs.portgroup.VSAN.name }}"
      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
      when: esxi.single_vswitch is true

#    - name: Migrate vmk0 (Mgmt) to the VDS
#      community.vmware.vmware_migrate_vmk:
#        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
#        username: "administrator@{{ vcenter.sso.domain_name }}"
#        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
#        validate_certs: false
#        esxi_hostname: "{{ item }}"
#        device: 'vmk0'
#        current_switch_name: 'vSwitch0'
#        current_portgroup_name: 'Management Network'
#        migrate_switch_name: "{{ vcenter.dvs.basename }}-0"
#        migrate_portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
#      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
#      register: result
#      until: result is not failed
#      retries: 5
#      when: esxi.single_vswitch is true

    - name: Add Management vmkernel port using static network type for vmk3
      community.vmware.vmware_vmkernel:
        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
        username: "administrator@{{ vcenter.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        validate_certs: false
        device: vmk3
        esxi_hostname: "{{ item.0 }}"
        dvswitch_name: "{{ vcenter.dvs.basename }}-0"
        portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
        network:
          type: 'static'
          ip_address: "{{ item.1 }}"
          subnet_mask: "{{ vcenter.dvs.portgroup.management.netmask }}"
        state: present
        enable_mgmt: True
      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips | zip(vcenter.dvs.portgroup.management.esxi_ips_temp) | list }}"
#      when: esxi.single_vswitch is true

#    - name: Add Management vmkernel port using static network type for vmk3
#      community.vmware.vmware_vmkernel:
#        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
#        username: "administrator@{{ vcenter.sso.domain_name }}"
#        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
#        validate_certs: false
#        device: vmk3
#        esxi_hostname: "{{ item.0 }}"
#        dvswitch_name: "{{ vcenter.dvs.basename }}-0"
#        portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
#        network:
#          type: 'static'
#          ip_address: "{{ item.1 }}"
#          subnet_mask: "{{ vcenter.dvs.portgroup.management.netmask }}"
#        state: present
#        enable_mgmt: True
#      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips | zip(vcenter.dvs.portgroup.management.esxi_ips_temp) | list }}"
#      when: esxi.single_vswitch is false

    - name: Add Management vmkernel port using static network type for vmk4
      community.vmware.vmware_vmkernel:
        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
        username: "administrator@{{ vcenter.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        validate_certs: false
        device: vmk4
        esxi_hostname: "{{ item }}"
        dvswitch_name: "{{ vcenter.dvs.basename }}-0"
        portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
        network:
          type: 'dhcp'
        state: present
        enable_mgmt: True
      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
#      when: esxi.single_vswitch is false

#    - name: Add Management vmkernel port using static network type for vmk4
#      community.vmware.vmware_vmkernel:
#        hostname: "{{ vcenter.name }}.{{ dns.domain}}"
#        username: "administrator@{{ vcenter.sso.domain_name }}"
#        password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
#        validate_certs: false
#        device: vmk4
#        esxi_hostname: "{{ item }}"
#        dvswitch_name: "{{ vcenter.dvs.basename }}-0"
#        portgroup_name: "{{ vcenter.dvs.portgroup.management.name }}-vmk"
#        network:
#          type: 'dhcp'
#        state: present
#        enable_mgmt: True
#      loop: "{{ vcenter.dvs.portgroup.management.esxi_ips }}"
#      when: esxi.single_vswitch is true