---
- hosts: localhost
  gather_facts: no
  collections:
    - vmware.ansible_for_nsxt

# ansible-galaxy collection install git+https://github.com/vmware/ansible-for-nsxt.git,master

  tasks:

    - name: Install NSX-T License
      nsxt_licenses:
        hostname: "{{ vcenter.dvs.portgroup.management.nsx_ip }}"
        username: "admin"
        password: "{{ lookup('env', 'TF_VAR_nsx_password') }}"
        validate_certs: no
        license_key: "{{ lookup('env', 'TF_VAR_nsx_license') }}"
        state: present
      ignore_errors: yes  # If license in already in use or not applicable, it will result in 'failure', so need to ensure we continue by ignoring the error
      no_log: true

    - name: Register NSX-T Compute Manager
      nsxt_fabric_compute_managers:
        hostname: "{{ vcenter.dvs.portgroup.management.nsx_ip }}"
        username: "admin"
        password: "{{ lookup('env', 'TF_VAR_nsx_password') }}"
        validate_certs: False
        display_name: "{{ vcenter.name }}.{{ dns.domain }}"
        server: "{{ vcenter.name }}.{{ dns.domain }}"
        origin_type: vCenter
        credential:
          credential_type: UsernamePasswordLoginCredential
          username: "administrator@{{ vcenter.sso.domain_name }}"
          password: "{{ lookup('env', 'TF_VAR_vcenter_password') }}"
        state: present