---
- hosts: localhost
  gather_facts: no

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Set variable avi_credentials
      set_fact:
        avi_credentials: >
          {'api_version': "{{ avi_version }}",
           'controller': "{{ avi_ip }}",
           'password': "{{ lookup('env', 'TF_VAR_avi_password') }}",
           'username': "admin"}
      when:
        - avi_version is defined
        - avi_ip is defined

    - name: Update user admin password
      community.network.avi_useraccount:
        controller: "{{ avi_credentials.controller }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        old_password: 58NFaGDJm(PJH0G
        api_version: "{{ avi_credentials.api_version }}"

    - name: Create Backup Configuration passphrase
      community.network.avi_backupconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        state: present
        backup_passphrase: "{{ lookup('env', 'TF_VAR_avi_backup_passphrase') }}"
        name: Backup-Configuration
        save_local: true

#    - name: Define ntp_servers
#      set_fact:
#        ntp_servers: "{{ ntp_servers | default([]) + [{ 'server': {'type': 'V4', 'addr': item}}] }}"
#
#    - name: Define dns_servers
#      set_fact:
#        server_list: "{{ server_list | default([]) + [{'type': 'V4', 'addr': item}] }}"
#      loop: "{{ controller.dns }}"
#      when:
#        - controller.dns is defined

    - name: Define avi_systemconfiguration
      set_fact:
        avi_systemconfiguration:
          global_tenant_config:
            se_in_provider_context: 'true'
            tenant_access_to_provider_se: 'true'
            tenant_vrf: 'false'
          welcome_workflow_complete: true
          ntp_configuration:
            ntp_servers:
              - server:
                 type: 'V4'
                 addr: "{{ ntp.server }}"
          dns_configuration:
            search_domain: "{{ dns.domain }}"
            server_list:
              - type: 'V4'
                addr: "{{ dns.nameserver }}"
          email_configuration:
            from_email: 'test@avicontroller.net'
            smtp_type: SMTP_LOCAL_HOST
      when:
        - ntp.server is defined
        - dns.domain is defined
        - dns.nameserver is defined


    - name: Configure Avi System parameters
      community.network.avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        global_tenant_config: "{{ avi_systemconfiguration.global_tenant_config }}"
        dns_configuration: "{{ avi_systemconfiguration.dns_configuration }}"
        ntp_configuration: "{{ avi_systemconfiguration.ntp_configuration }}"
        email_configuration: "{{ avi_systemconfiguration.email_configuration }}"
        welcome_workflow_complete: "{{ avi_systemconfiguration.welcome_workflow_complete }}"
      when:
        - avi_systemconfiguration is defined
